"""Map type profiles and family configuration for the generation pipeline."""

FAMILIES: dict[str, dict] = {
    "underground": {"cave_carver": True, "terrain_preset": "dungeon", "corridor_default": "carved"},
    "fortification": {"cave_carver": False, "terrain_preset": None, "corridor_default": "built"},
    "settlement": {"cave_carver": False, "terrain_preset": None, "corridor_default": "road"},
    "interior": {"cave_carver": False, "terrain_preset": "flat_floor", "corridor_default": "hallway"},
    "outdoor": {
        "cave_carver": True,
        "terrain_preset": None,
        "corridor_default": "natural",
        "carve_threshold": 0.35,
        "passage_threshold": 0.40,
        "smoothing_iterations": 2,
    },
    "large_scale": {
        "cave_carver": True,
        "terrain_preset": None,
        "corridor_default": "road",
        "carve_threshold": 0.40,
        "passage_threshold": 0.45,
        "smoothing_iterations": 2,
    },
}

MAP_TYPE_PROFILES: dict[str, dict] = {
    # -------------------------------------------------------------------------
    # Underground (6)
    # -------------------------------------------------------------------------
    "dungeon": {
        "family": "underground",
        "topology_preference": ["hub_and_spoke", "loop_based"],
        "size_topology_override": {
            "small_encounter": "linear_with_branches",
            "large": "hybrid",
        },
        "room_pool": {
            "required": ["entrance", "boss_lair"],
            "common": ["guard_room", "barracks", "armory", "storage", "cell"],
            "uncommon": ["shrine", "alchemy_lab", "library", "crypt"],
            "rare": ["treasure_vault", "secret_chamber", "portal_room"],
        },
        "creature_table": {
            "common": [("skeleton", 3), ("goblin", 2), ("rat", 2)],
            "uncommon": [("orc", 2), ("zombie", 1)],
            "boss": [("ogre", 1), ("troll", 1)],
        },
        "trap_density": 0.3,
        "loot_tier": "medium",
        "dressing_palette": "dungeon",
        "biome_override": "dungeon",
        "z_levels": {"min": 1, "max": 4},
        "corridor_style": "carved",
        "door_frequency": 0.6,
        "secret_room_chance": 0.15,
    },
    "cave": {
        "family": "underground",
        "topology_preference": ["linear_with_branches", "loop_based"],
        "size_topology_override": {},
        "room_pool": {
            "required": ["entrance"],
            "common": ["storage", "cell"],
            "uncommon": ["shrine", "crypt"],
            "rare": ["treasure_vault", "secret_chamber"],
        },
        "creature_table": {
            "common": [("rat", 3), ("wolf", 2)],
            "uncommon": [("goblin", 2)],
            "boss": [("ogre", 1)],
        },
        "trap_density": 0.15,
        "loot_tier": "low",
        "dressing_palette": "dungeon",
        "biome_override": "cave",
        "z_levels": {"min": 1, "max": 3},
        "corridor_style": "natural",
        "door_frequency": 0.1,
        "secret_room_chance": 0.1,
    },
    "mine": {
        "family": "underground",
        "topology_preference": ["linear_with_branches"],
        "size_topology_override": {},
        "room_pool": {
            "required": ["entrance"],
            "common": ["storage", "cell"],
            "uncommon": ["armory"],
            "rare": ["treasure_vault"],
        },
        "creature_table": {
            "common": [("goblin", 3), ("rat", 2)],
            "uncommon": [("orc", 1)],
            "boss": [("ogre", 1)],
        },
        "trap_density": 0.2,
        "loot_tier": "medium",
        "dressing_palette": "dungeon",
        "biome_override": "cave",
        "z_levels": {"min": 1, "max": 3},
        "corridor_style": "carved",
        "door_frequency": 0.2,
        "secret_room_chance": 0.1,
    },
    "maze": {
        "family": "underground",
        "topology_preference": ["loop_based"],
        "size_topology_override": {},
        "room_pool": {
            "required": ["entrance"],
            "common": ["corridor_hub"],
            "uncommon": ["shrine"],
            "rare": ["treasure_vault", "secret_chamber"],
        },
        "creature_table": {
            "common": [("skeleton", 2), ("zombie", 2)],
            "uncommon": [("orc", 1)],
            "boss": [("troll", 1)],
        },
        "trap_density": 0.4,
        "loot_tier": "medium",
        "dressing_palette": "dungeon",
        "biome_override": "dungeon",
        "z_levels": {"min": 1, "max": 1},
        "corridor_style": "carved",
        "door_frequency": 0.3,
        "secret_room_chance": 0.2,
    },
    "crypt": {
        "family": "underground",
        "topology_preference": ["linear_with_branches", "hub_and_spoke"],
        "size_topology_override": {},
        "room_pool": {
            "required": ["entrance", "boss_lair"],
            "common": ["crypt", "cell", "storage"],
            "uncommon": ["shrine", "library"],
            "rare": ["treasure_vault", "secret_chamber"],
        },
        "creature_table": {
            "common": [("skeleton", 4), ("zombie", 2)],
            "uncommon": [("orc", 1)],
            "boss": [("troll", 1)],
        },
        "trap_density": 0.35,
        "loot_tier": "medium",
        "dressing_palette": "dungeon",
        "biome_override": "dungeon",
        "z_levels": {"min": 1, "max": 3},
        "corridor_style": "carved",
        "door_frequency": 0.5,
        "secret_room_chance": 0.15,
    },
    "tomb": {
        "family": "underground",
        "topology_preference": ["linear_with_branches"],
        "size_topology_override": {},
        "room_pool": {
            "required": ["entrance", "boss_lair"],
            "common": ["crypt", "guard_room", "storage"],
            "uncommon": ["shrine", "alchemy_lab", "treasure_vault"],
            "rare": ["secret_chamber", "portal_room"],
        },
        "creature_table": {
            "common": [("skeleton", 3), ("zombie", 2)],
            "uncommon": [("orc", 1)],
            "boss": [("troll", 1), ("ogre", 1)],
        },
        "trap_density": 0.4,
        "loot_tier": "high",
        "dressing_palette": "dungeon",
        "biome_override": "dungeon",
        "z_levels": {"min": 1, "max": 3},
        "corridor_style": "carved",
        "door_frequency": 0.7,
        "secret_room_chance": 0.2,
    },
    # -------------------------------------------------------------------------
    # Fortification (4)
    # -------------------------------------------------------------------------
    "castle": {
        "family": "fortification",
        "topology_preference": ["hub_and_spoke", "loop_based"],
        "size_topology_override": {},
        "room_pool": {
            "required": ["entrance", "boss_lair"],
            "common": ["guard_room", "barracks", "armory", "storage"],
            "uncommon": ["shrine", "library", "treasure_vault"],
            "rare": ["secret_chamber", "portal_room"],
        },
        "creature_table": {
            "common": [("guard", 4), ("bandit", 2)],
            "uncommon": [("orc", 2)],
            "boss": [("ogre", 1), ("troll", 1)],
        },
        "trap_density": 0.25,
        "loot_tier": "high",
        "dressing_palette": "fortification",
        "biome_override": None,
        "z_levels": {"min": 1, "max": 5},
        "corridor_style": "built",
        "door_frequency": 0.8,
        "secret_room_chance": 0.1,
    },
    "fort": {
        "family": "fortification",
        "topology_preference": ["hub_and_spoke"],
        "size_topology_override": {},
        "room_pool": {
            "required": ["entrance"],
            "common": ["guard_room", "barracks", "armory", "storage"],
            "uncommon": ["shrine"],
            "rare": ["treasure_vault"],
        },
        "creature_table": {
            "common": [("guard", 3), ("bandit", 2)],
            "uncommon": [("orc", 1)],
            "boss": [("ogre", 1)],
        },
        "trap_density": 0.2,
        "loot_tier": "medium",
        "dressing_palette": "fortification",
        "biome_override": None,
        "z_levels": {"min": 1, "max": 3},
        "corridor_style": "built",
        "door_frequency": 0.7,
        "secret_room_chance": 0.05,
    },
    "tower": {
        "family": "fortification",
        "topology_preference": ["linear_with_branches"],
        "size_topology_override": {},
        "room_pool": {
            "required": ["entrance", "boss_lair"],
            "common": ["guard_room", "library", "storage"],
            "uncommon": ["alchemy_lab", "shrine"],
            "rare": ["treasure_vault", "portal_room"],
        },
        "creature_table": {
            "common": [("guard", 2), ("skeleton", 2)],
            "uncommon": [("orc", 1)],
            "boss": [("troll", 1)],
        },
        "trap_density": 0.3,
        "loot_tier": "high",
        "dressing_palette": "fortification",
        "biome_override": None,
        "z_levels": {"min": 3, "max": 6},
        "corridor_style": "built",
        "door_frequency": 0.8,
        "secret_room_chance": 0.1,
    },
    "outpost": {
        "family": "fortification",
        "topology_preference": ["linear_with_branches"],
        "size_topology_override": {},
        "room_pool": {
            "required": ["entrance"],
            "common": ["guard_room", "barracks", "storage"],
            "uncommon": ["armory"],
            "rare": ["secret_chamber"],
        },
        "creature_table": {
            "common": [("guard", 2), ("bandit", 1)],
            "uncommon": [("orc", 1)],
            "boss": [],
        },
        "trap_density": 0.1,
        "loot_tier": "low",
        "dressing_palette": "fortification",
        "biome_override": None,
        "z_levels": {"min": 1, "max": 2},
        "corridor_style": "built",
        "door_frequency": 0.6,
        "secret_room_chance": 0.05,
    },
    # -------------------------------------------------------------------------
    # Settlement (5)
    # -------------------------------------------------------------------------
    "village": {
        "family": "settlement",
        "topology_preference": ["hub_and_spoke"],
        "size_topology_override": {},
        "room_pool": {
            "required": ["entrance", "town_square"],
            "common": ["house", "tavern", "shop", "farm", "well"],
            "uncommon": ["blacksmith", "temple", "inn", "stable"],
            "rare": ["manor", "hidden_cellar"],
        },
        "creature_table": {
            "common": [("rat", 2)],
            "uncommon": [("wolf", 1), ("bandit", 1)],
            "boss": [],
        },
        "trap_density": 0.0,
        "loot_tier": "low",
        "dressing_palette": "settlement",
        "biome_override": None,
        "z_levels": {"min": 1, "max": 2},
        "corridor_style": "road",
        "door_frequency": 0.9,
        "secret_room_chance": 0.05,
    },
    "town": {
        "family": "settlement",
        "topology_preference": ["hub_and_spoke"],
        "size_topology_override": {},
        "room_pool": {
            "required": ["entrance", "town_square"],
            "common": ["house", "tavern", "shop", "inn"],
            "uncommon": ["blacksmith", "stable", "shrine"],
            "rare": ["manor", "hidden_cellar"],
        },
        "creature_table": {
            "common": [("rat", 2), ("bandit", 1)],
            "uncommon": [("guard", 1)],
            "boss": [],
        },
        "trap_density": 0.0,
        "loot_tier": "low",
        "dressing_palette": "settlement",
        "biome_override": None,
        "z_levels": {"min": 1, "max": 2},
        "corridor_style": "road",
        "door_frequency": 0.9,
        "secret_room_chance": 0.05,
    },
    "city": {
        "family": "settlement",
        "topology_preference": ["hub_and_spoke", "loop_based"],
        "size_topology_override": {},
        "room_pool": {
            "required": ["entrance", "town_square"],
            "common": ["house", "tavern", "shop", "inn"],
            "uncommon": ["blacksmith", "shrine", "manor"],
            "rare": ["hidden_cellar", "secret_chamber"],
        },
        "creature_table": {
            "common": [("bandit", 2), ("guard", 2)],
            "uncommon": [("orc", 1)],
            "boss": [],
        },
        "trap_density": 0.05,
        "loot_tier": "medium",
        "dressing_palette": "settlement",
        "biome_override": None,
        "z_levels": {"min": 1, "max": 3},
        "corridor_style": "road",
        "door_frequency": 0.9,
        "secret_room_chance": 0.05,
    },
    "camp": {
        "family": "settlement",
        "topology_preference": ["linear_with_branches"],
        "size_topology_override": {},
        "room_pool": {
            "required": ["entrance"],
            "common": ["storage", "safe_haven"],
            "uncommon": ["guard_room"],
            "rare": [],
        },
        "creature_table": {
            "common": [("rat", 1), ("wolf", 1)],
            "uncommon": [("bandit", 1)],
            "boss": [],
        },
        "trap_density": 0.0,
        "loot_tier": "low",
        "dressing_palette": "settlement",
        "biome_override": None,
        "z_levels": {"min": 1, "max": 1},
        "corridor_style": "natural",
        "door_frequency": 0.2,
        "secret_room_chance": 0.0,
    },
    "rest_area": {
        "family": "settlement",
        "topology_preference": ["linear_with_branches"],
        "size_topology_override": {},
        "room_pool": {
            "required": ["entrance", "safe_haven"],
            "common": ["storage"],
            "uncommon": [],
            "rare": [],
        },
        "creature_table": {
            "common": [("rat", 1)],
            "uncommon": [],
            "boss": [],
        },
        "trap_density": 0.0,
        "loot_tier": "low",
        "dressing_palette": "settlement",
        "biome_override": None,
        "z_levels": {"min": 1, "max": 1},
        "corridor_style": "natural",
        "door_frequency": 0.1,
        "secret_room_chance": 0.0,
    },
    # -------------------------------------------------------------------------
    # Interior (10)
    # -------------------------------------------------------------------------
    "tavern": {
        "family": "interior",
        "topology_preference": ["linear_with_branches"],
        "size_topology_override": {},
        "room_pool": {
            "required": ["entrance", "common_room"],
            "common": ["kitchen", "bar", "guest_room", "storage"],
            "uncommon": ["cellar", "owner_quarters", "stable"],
            "rare": ["secret_chamber", "gambling_den"],
        },
        "creature_table": {
            "common": [("rat", 1)],
            "uncommon": [("bandit", 2)],
            "boss": [],
        },
        "trap_density": 0.05,
        "loot_tier": "low",
        "dressing_palette": "tavern",
        "biome_override": None,
        "z_levels": {"min": 1, "max": 2},
        "corridor_style": "hallway",
        "door_frequency": 0.95,
        "secret_room_chance": 0.1,
    },
    "prison": {
        "family": "interior",
        "topology_preference": ["linear_with_branches", "hub_and_spoke"],
        "size_topology_override": {},
        "room_pool": {
            "required": ["entrance"],
            "common": ["cell", "guard_room", "storage"],
            "uncommon": ["armory", "boss_lair"],
            "rare": ["secret_chamber", "treasure_vault"],
        },
        "creature_table": {
            "common": [("guard", 3), ("bandit", 2)],
            "uncommon": [("orc", 1)],
            "boss": [("ogre", 1)],
        },
        "trap_density": 0.15,
        "loot_tier": "medium",
        "dressing_palette": "dungeon",
        "biome_override": None,
        "z_levels": {"min": 1, "max": 2},
        "corridor_style": "hallway",
        "door_frequency": 0.95,
        "secret_room_chance": 0.1,
    },
    "library": {
        "family": "interior",
        "topology_preference": ["linear_with_branches"],
        "size_topology_override": {},
        "room_pool": {
            "required": ["entrance"],
            "common": ["library", "storage"],
            "uncommon": ["shrine", "alchemy_lab"],
            "rare": ["secret_chamber", "treasure_vault"],
        },
        "creature_table": {
            "common": [("skeleton", 1)],
            "uncommon": [],
            "boss": [],
        },
        "trap_density": 0.15,
        "loot_tier": "medium",
        "dressing_palette": "dungeon",
        "biome_override": None,
        "z_levels": {"min": 1, "max": 2},
        "corridor_style": "hallway",
        "door_frequency": 0.9,
        "secret_room_chance": 0.15,
    },
    "throne_room": {
        "family": "interior",
        "topology_preference": ["hub_and_spoke"],
        "size_topology_override": {},
        "room_pool": {
            "required": ["entrance", "boss_lair"],
            "common": ["guard_room", "storage"],
            "uncommon": ["armory", "treasure_vault"],
            "rare": ["secret_chamber"],
        },
        "creature_table": {
            "common": [("guard", 4)],
            "uncommon": [("orc", 1)],
            "boss": [("troll", 1)],
        },
        "trap_density": 0.2,
        "loot_tier": "high",
        "dressing_palette": "fortification",
        "biome_override": None,
        "z_levels": {"min": 1, "max": 2},
        "corridor_style": "hallway",
        "door_frequency": 0.9,
        "secret_room_chance": 0.1,
    },
    "shop": {
        "family": "interior",
        "topology_preference": ["linear_with_branches"],
        "size_topology_override": {},
        "room_pool": {
            "required": ["entrance"],
            "common": ["storage", "shop"],
            "uncommon": ["owner_quarters"],
            "rare": ["secret_chamber"],
        },
        "creature_table": {
            "common": [("rat", 1)],
            "uncommon": [("bandit", 1)],
            "boss": [],
        },
        "trap_density": 0.05,
        "loot_tier": "low",
        "dressing_palette": "tavern",
        "biome_override": None,
        "z_levels": {"min": 1, "max": 1},
        "corridor_style": "hallway",
        "door_frequency": 0.9,
        "secret_room_chance": 0.05,
    },
    "shopping_center": {
        "family": "interior",
        "topology_preference": ["hub_and_spoke"],
        "size_topology_override": {},
        "room_pool": {
            "required": ["entrance", "town_square"],
            "common": ["shop", "storage"],
            "uncommon": ["tavern", "blacksmith"],
            "rare": ["secret_chamber"],
        },
        "creature_table": {
            "common": [("bandit", 2), ("rat", 2)],
            "uncommon": [("guard", 1)],
            "boss": [],
        },
        "trap_density": 0.05,
        "loot_tier": "medium",
        "dressing_palette": "tavern",
        "biome_override": None,
        "z_levels": {"min": 1, "max": 2},
        "corridor_style": "hallway",
        "door_frequency": 0.9,
        "secret_room_chance": 0.05,
    },
    "factory": {
        "family": "interior",
        "topology_preference": ["hub_and_spoke"],
        "size_topology_override": {},
        "room_pool": {
            "required": ["entrance"],
            "common": ["storage", "guard_room"],
            "uncommon": ["armory", "boss_lair"],
            "rare": ["secret_chamber"],
        },
        "creature_table": {
            "common": [("bandit", 2), ("guard", 1)],
            "uncommon": [("orc", 1)],
            "boss": [("ogre", 1)],
        },
        "trap_density": 0.1,
        "loot_tier": "medium",
        "dressing_palette": "dungeon",
        "biome_override": None,
        "z_levels": {"min": 1, "max": 2},
        "corridor_style": "hallway",
        "door_frequency": 0.8,
        "secret_room_chance": 0.05,
    },
    "temple": {
        "family": "interior",
        "topology_preference": ["hub_and_spoke"],
        "size_topology_override": {},
        "room_pool": {
            "required": ["entrance", "shrine"],
            "common": ["library", "storage", "cell"],
            "uncommon": ["crypt", "alchemy_lab", "treasure_vault"],
            "rare": ["boss_lair", "secret_chamber", "portal_room"],
        },
        "creature_table": {
            "common": [("guard", 2), ("skeleton", 1)],
            "uncommon": [("orc", 1)],
            "boss": [("troll", 1)],
        },
        "trap_density": 0.2,
        "loot_tier": "medium",
        "dressing_palette": "dungeon",
        "biome_override": None,
        "z_levels": {"min": 1, "max": 3},
        "corridor_style": "hallway",
        "door_frequency": 0.85,
        "secret_room_chance": 0.1,
    },
    "church": {
        "family": "interior",
        "topology_preference": ["linear_with_branches"],
        "size_topology_override": {},
        "room_pool": {
            "required": ["entrance", "shrine"],
            "common": ["library", "storage"],
            "uncommon": ["crypt"],
            "rare": ["secret_chamber"],
        },
        "creature_table": {
            "common": [("guard", 1)],
            "uncommon": [("skeleton", 1)],
            "boss": [],
        },
        "trap_density": 0.05,
        "loot_tier": "low",
        "dressing_palette": "dungeon",
        "biome_override": None,
        "z_levels": {"min": 1, "max": 2},
        "corridor_style": "hallway",
        "door_frequency": 0.9,
        "secret_room_chance": 0.05,
    },
    "treasure_room": {
        "family": "interior",
        "topology_preference": ["linear_with_branches"],
        "size_topology_override": {},
        "room_pool": {
            "required": ["entrance", "treasure_vault"],
            "common": ["guard_room", "storage"],
            "uncommon": ["armory"],
            "rare": ["secret_chamber", "boss_lair"],
        },
        "creature_table": {
            "common": [("guard", 2)],
            "uncommon": [("orc", 2), ("ogre", 1)],
            "boss": [("troll", 1)],
        },
        "trap_density": 0.5,
        "loot_tier": "legendary",
        "dressing_palette": "dungeon",
        "biome_override": None,
        "z_levels": {"min": 1, "max": 2},
        "corridor_style": "hallway",
        "door_frequency": 0.8,
        "secret_room_chance": 0.2,
    },
    # -------------------------------------------------------------------------
    # Outdoor (5)
    # -------------------------------------------------------------------------
    "wilderness": {
        "family": "outdoor",
        "topology_preference": ["linear_with_branches"],
        "size_topology_override": {},
        "room_pool": {
            "required": ["entrance"],
            "common": ["safe_haven", "storage"],
            "uncommon": ["shrine"],
            "rare": ["secret_chamber", "treasure_vault"],
        },
        "creature_table": {
            "common": [("wolf", 3), ("rat", 2)],
            "uncommon": [("bandit", 2)],
            "boss": [("ogre", 1)],
        },
        "trap_density": 0.1,
        "loot_tier": "low",
        "dressing_palette": "outdoor",
        "biome_override": None,
        "z_levels": {"min": 1, "max": 1},
        "corridor_style": "natural",
        "door_frequency": 0.0,
        "secret_room_chance": 0.1,
    },
    "graveyard": {
        "family": "outdoor",
        "topology_preference": ["linear_with_branches"],
        "size_topology_override": {},
        "room_pool": {
            "required": ["entrance"],
            "common": ["crypt", "shrine"],
            "uncommon": ["guard_room"],
            "rare": ["treasure_vault", "secret_chamber", "boss_lair"],
        },
        "creature_table": {
            "common": [("zombie", 3), ("skeleton", 2)],
            "uncommon": [("orc", 1)],
            "boss": [("troll", 1)],
        },
        "trap_density": 0.15,
        "loot_tier": "medium",
        "dressing_palette": "outdoor",
        "biome_override": None,
        "z_levels": {"min": 1, "max": 2},
        "corridor_style": "natural",
        "door_frequency": 0.3,
        "secret_room_chance": 0.1,
    },
    "dock": {
        "family": "outdoor",
        "topology_preference": ["linear_with_branches"],
        "size_topology_override": {},
        "room_pool": {
            "required": ["entrance"],
            "common": ["storage", "shop"],
            "uncommon": ["tavern", "guard_room"],
            "rare": ["secret_chamber"],
        },
        "creature_table": {
            "common": [("bandit", 2), ("rat", 2)],
            "uncommon": [("guard", 1)],
            "boss": [],
        },
        "trap_density": 0.05,
        "loot_tier": "low",
        "dressing_palette": "outdoor",
        "biome_override": None,
        "z_levels": {"min": 1, "max": 1},
        "corridor_style": "natural",
        "door_frequency": 0.3,
        "secret_room_chance": 0.05,
    },
    "arena": {
        "family": "outdoor",
        "topology_preference": ["hub_and_spoke"],
        "size_topology_override": {},
        "room_pool": {
            "required": ["entrance", "arena"],
            "common": ["guard_room", "storage"],
            "uncommon": ["armory", "cell"],
            "rare": ["treasure_vault", "boss_lair"],
        },
        "creature_table": {
            "common": [("guard", 2), ("guard", 2)],
            "uncommon": [("orc", 2)],
            "boss": [("ogre", 1), ("troll", 1)],
        },
        "trap_density": 0.1,
        "loot_tier": "medium",
        "dressing_palette": "outdoor",
        "biome_override": None,
        "z_levels": {"min": 1, "max": 1},
        "corridor_style": "built",
        "door_frequency": 0.5,
        "secret_room_chance": 0.05,
    },
    "crash_site": {
        "family": "outdoor",
        "topology_preference": ["linear_with_branches"],
        "size_topology_override": {},
        "room_pool": {
            "required": ["entrance"],
            "common": ["storage"],
            "uncommon": ["treasure_vault"],
            "rare": ["secret_chamber"],
        },
        "creature_table": {
            "common": [("rat", 2), ("wolf", 1)],
            "uncommon": [("bandit", 2)],
            "boss": [],
        },
        "trap_density": 0.1,
        "loot_tier": "medium",
        "dressing_palette": "outdoor",
        "biome_override": None,
        "z_levels": {"min": 1, "max": 1},
        "corridor_style": "natural",
        "door_frequency": 0.1,
        "secret_room_chance": 0.1,
    },
    # -------------------------------------------------------------------------
    # Large-scale (4)
    # -------------------------------------------------------------------------
    "biomes": {
        "family": "large_scale",
        "topology_preference": ["hub_and_spoke"],
        "size_topology_override": {},
        "room_pool": {
            "required": ["entrance", "town_square"],
            "common": ["house", "shop", "safe_haven"],
            "uncommon": ["shrine", "tavern"],
            "rare": ["treasure_vault", "boss_lair"],
        },
        "creature_table": {
            "common": [("wolf", 2), ("bandit", 2)],
            "uncommon": [("orc", 1)],
            "boss": [("ogre", 1)],
        },
        "trap_density": 0.1,
        "loot_tier": "medium",
        "dressing_palette": "outdoor",
        "biome_override": None,
        "z_levels": {"min": 1, "max": 1},
        "corridor_style": "road",
        "door_frequency": 0.3,
        "secret_room_chance": 0.05,
    },
    "region": {
        "family": "large_scale",
        "topology_preference": ["hub_and_spoke", "loop_based"],
        "size_topology_override": {},
        "room_pool": {
            "required": ["entrance", "town_square"],
            "common": ["house", "shop", "tavern", "safe_haven"],
            "uncommon": ["shrine", "guard_room", "blacksmith"],
            "rare": ["treasure_vault", "boss_lair", "secret_chamber"],
        },
        "creature_table": {
            "common": [("wolf", 2), ("bandit", 2), ("guard", 1)],
            "uncommon": [("orc", 2)],
            "boss": [("ogre", 1), ("troll", 1)],
        },
        "trap_density": 0.1,
        "loot_tier": "medium",
        "dressing_palette": "outdoor",
        "biome_override": None,
        "z_levels": {"min": 1, "max": 2},
        "corridor_style": "road",
        "door_frequency": 0.3,
        "secret_room_chance": 0.05,
    },
    "open_world": {
        "family": "large_scale",
        "topology_preference": ["hybrid"],
        "size_topology_override": {},
        "room_pool": {
            "required": ["entrance"],
            "common": ["town_square", "house", "shop", "tavern", "safe_haven"],
            "uncommon": ["shrine", "guard_room", "blacksmith", "boss_lair"],
            "rare": ["treasure_vault", "secret_chamber", "portal_room"],
        },
        "creature_table": {
            "common": [("wolf", 2), ("bandit", 2), ("guard", 2)],
            "uncommon": [("orc", 2), ("goblin", 2)],
            "boss": [("ogre", 1), ("troll", 1)],
        },
        "trap_density": 0.1,
        "loot_tier": "medium",
        "dressing_palette": "outdoor",
        "biome_override": None,
        "z_levels": {"min": 1, "max": 3},
        "corridor_style": "road",
        "door_frequency": 0.3,
        "secret_room_chance": 0.1,
    },
    "world_box": {
        "family": "large_scale",
        "topology_preference": ["hybrid"],
        "size_topology_override": {},
        "room_pool": {
            "required": ["entrance"],
            "common": ["town_square", "house", "shop", "tavern", "safe_haven"],
            "uncommon": ["shrine", "guard_room", "boss_lair"],
            "rare": ["treasure_vault", "secret_chamber", "portal_room"],
        },
        "creature_table": {
            "common": [("wolf", 2), ("bandit", 2), ("guard", 2)],
            "uncommon": [("orc", 2), ("goblin", 2)],
            "boss": [("ogre", 1), ("troll", 1)],
        },
        "trap_density": 0.1,
        "loot_tier": "medium",
        "dressing_palette": "outdoor",
        "biome_override": None,
        "z_levels": {"min": 1, "max": 3},
        "corridor_style": "road",
        "door_frequency": 0.3,
        "secret_room_chance": 0.1,
    },
}


def get_profile(map_type: str) -> dict:
    """Return the profile dict for the given map type. Raises KeyError if unknown."""
    return MAP_TYPE_PROFILES[map_type]


def get_family(map_type: str) -> str:
    """Return the family name for the given map type. Raises KeyError if unknown."""
    return MAP_TYPE_PROFILES[map_type]["family"]
